MASLLIB=-L$(HOME)/git/masl/install/lib
MASLINCLUDE=-I$(HOME)/git/masl/install/include
TRACKING_LOC=../Tracking
LOG_LOC=../../../../masl/EEs/LOG
CXXFLAGS=$(MASLINCLUDE) -I$(TRACKING_LOC)/include -I$(LOG_LOC)/include -Iinclude -fPIC -w -fpermissive -Wl,--no-as-needed
OUTDIR=bin
SRCDIR=src

ARTIFACTS=                $(OUTDIR)/libUI_interface.so \
                          $(OUTDIR)/libUI.so \
                          $(OUTDIR)/libUI_sqlite.so \
                          $(OUTDIR)/libUI_inspector.so \
                          $(OUTDIR)/libUI_if_inspector.so \
                          $(OUTDIR)/libUI_transient.so \
                          $(OUTDIR)/UI_transient_standalone

UI_interface_SOURCES=     $(SRCDIR)/__UI_types.cc \
                          $(SRCDIR)/__UI_interface.cc
UI_interface_OBJECTS=     $(UI_interface_SOURCES:.cc=.o)
UI_interface_LIBS=        -lswa -lasn1 -lboost_system

UI_SOURCES=               $(SRCDIR)/__UI.cc \
                          $(SRCDIR)/__UI_private_types.cc \
                          $(SRCDIR)/__UI__TestCase.cc \
                          $(SRCDIR)/__UI__UI.cc \
                          $(SRCDIR)/__UI__UIConstants.cc \
                          $(SRCDIR)/__UI__TRACK.cc \
                          $(SRCDIR)/__UI__TestCasePopulation.cc \
                          $(SRCDIR)/__UI__UIPopulation.cc \
                          $(SRCDIR)/__UI__UIConstantsPopulation.cc \
                          $(SRCDIR)/__UI__TRACK__setTargetPressed.cc \
                          $(SRCDIR)/__UI__TRACK__startStopPressed.cc \
                          $(SRCDIR)/__UI__TRACK__lapResetPressed.cc \
                          $(SRCDIR)/__UI__TRACK__lightPressed.cc \
                          $(SRCDIR)/__UI__TRACK__modePressed.cc \
                          $(SRCDIR)/__UI__TRACK__newGoalSpec.cc \
                          $(SRCDIR)/__UI__TestCase__execute.cc \
                          $(SRCDIR)/__UI__TestCase__pressStartStop.cc \
                          $(SRCDIR)/__UI__TestCase__testCaseFinished.cc \
                          $(SRCDIR)/__UI__TestCase__initialize.cc \
                          $(SRCDIR)/__UI__TestCase__Idle.cc \
                          $(SRCDIR)/__UI__UI__connect.cc \
                          $(SRCDIR)/__UI__UI__poll.cc \
                          $(SRCDIR)/__UI__UI__setData.cc \
                          $(SRCDIR)/__UI__UI__setIndicator.cc \
                          $(SRCDIR)/__UI__UI__setTime.cc \
                          $(SRCDIR)/__UI__UI__initialize.cc \
                          $(SRCDIR)/__UI__UI__running.cc \
                          $(SRCDIR)/__UI__UI__setTargetPressed.cc \
                          $(SRCDIR)/__UI__UI__startStopPresssed.cc \
                          $(SRCDIR)/__UI__UI__lapResetPressed.cc \
                          $(SRCDIR)/__UI__UI__lightPressed.cc \
                          $(SRCDIR)/__UI__UI__modePressed.cc \
                          $(SRCDIR)/__UI__UIConstants__initialize.cc \
                          $(SRCDIR)/__UI__setData.cc \
                          $(SRCDIR)/__UI__setIndicator.cc \
                          $(SRCDIR)/__UI__setTime.cc \
                          $(SRCDIR)/__UI__startTest.cc \
                          $(SRCDIR)/__UI__RunTestCase.cc \
                          $(SRCDIR)/__UI__createGoals_1.cc \
                          $(SRCDIR)/__UI__init.cc \
                          $(SRCDIR)/__UI__sendLapResetPressed.cc \
                          $(SRCDIR)/__UI__sendLightPressed.cc \
                          $(SRCDIR)/__UI__sendModePressed.cc \
                          $(SRCDIR)/__UI__sendStartStopPressed.cc \
                          $(SRCDIR)/__UI__sendTargetPressed.cc \
                          $(SRCDIR)/UI_GuiBridge_bridge.c
UI_OBJECTS=               $(UI_SOURCES:.cc=.o)
UI_LIBS=                  -lswa -lUI_interface -lTracking_interface -lLOG_interface

UI_sqlite_SOURCES=        $(SRCDIR)/Sqlite__UI__TestCase.cc \
                          $(SRCDIR)/Sqlite__UI__TestCasePopulation.cc \
                          $(SRCDIR)/Sqlite__UI__TestCaseMapper.cc \
                          $(SRCDIR)/Sqlite__UI__TestCaseMapperSql.cc \
                          $(SRCDIR)/Sqlite__UI__UI.cc \
                          $(SRCDIR)/Sqlite__UI__UIPopulation.cc \
                          $(SRCDIR)/Sqlite__UI__UIMapper.cc \
                          $(SRCDIR)/Sqlite__UI__UIMapperSql.cc \
                          $(SRCDIR)/Sqlite__UI__UIConstants.cc \
                          $(SRCDIR)/Sqlite__UI__UIConstantsPopulation.cc \
                          $(SRCDIR)/Sqlite__UI__UIConstantsMapper.cc \
                          $(SRCDIR)/Sqlite__UI__UIConstantsMapperSql.cc
UI_sqlite_OBJECTS=        $(UI_sqlite_SOURCES:.cc=.o)
UI_sqlite_LIBS=           -lUI -lsqlite -lasn1 -lswa -lsql -lboost_system -lUI_interface

UI_metadata_SOURCES=      $(SRCDIR)/MetaData__UI.cc
UI_metadata_OBJECTS=      $(UI_metadata_SOURCES:.cc=.o)
UI_metadata_LIBS=         -lMetaData -lswa -lUI -lTracking_interface -lUI_interface -lTracking_metadata

UI_if_metadata_SOURCES=   $(SRCDIR)/MetaData__if__UI.cc
UI_if_metadata_OBJECTS=   $(UI_if_metadata_SOURCES:.cc=.o)
UI_if_metadata_LIBS=      -lMetaData -lswa -lUI_metadata -lUI_interface

UI_inspector_SOURCES=     $(SRCDIR)/Inspector__UI.cc \
                          $(SRCDIR)/Inspector_private_types__UI.cc \
                          $(SRCDIR)/Inspector__UI__TestCase.cc \
                          $(SRCDIR)/Inspector__UI__UI.cc \
                          $(SRCDIR)/Inspector__UI__UIConstants.cc \
                          $(SRCDIR)/Inspector__UI__TRACK.cc
UI_inspector_OBJECTS=     $(UI_inspector_SOURCES:.cc=.o)
UI_inspector_LIBS=        -lUI_if_inspector -lInspector -lswa -lUI -lboost_system -lUI_interface -lTracking_interface

UI_if_inspector_SOURCES=  $(SRCDIR)/Inspector_types__UI.cc
UI_if_inspector_OBJECTS=  $(UI_if_inspector_SOURCES:.cc=.o)
UI_if_inspector_LIBS=     -lInspector -lUI_interface

UI_transient_SOURCES=     $(SRCDIR)/Transient__UI__TestCase.cc \
                          $(SRCDIR)/Transient__UI__TestCasePopulation.cc \
                          $(SRCDIR)/Transient__UI__UI.cc \
                          $(SRCDIR)/Transient__UI__UIPopulation.cc \
                          $(SRCDIR)/Transient__UI__UIConstants.cc \
                          $(SRCDIR)/Transient__UI__UIConstantsPopulation.cc
UI_transient_OBJECTS=     $(UI_transient_SOURCES:.cc=.o)
UI_transient_LIBS=        -ltransient -lUI -lswa -lboost_system

UI_transient_standalone_SOURCES=  $(SRCDIR)/initStandalone.cc
UI_transient_standalone_OBJECTS=  $(UI_transient_standalone_SOURCES:.cc=.o)
UI_transient_standalone_LIBS=     -lUI_transient -lUI -lUI_interface -lTracking_transient -lTracking -lTracking_interface \
                                  -lLOG_transient -lLOG -lLOG_interface -lLogger_transient -lLogger -lLogger_interface \
                                  -lFormat_transient -lFormat -lFormat_interface -lswa -ltransient -lasn1 -llogging

all: $(ARTIFACTS)

$(OUTDIR)/UI_transient_standalone: $(UI_transient_standalone_OBJECTS) $(OUTDIR)/libUI_transient.so $(OUTDIR)/libUI.so $(OUTDIR)/libUI_interface.so
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -L$(TRACKING_LOC)/bin -L$(LOG_LOC)/bin $(UI_transient_standalone_OBJECTS) -o $@ $(UI_transient_standalone_LIBS)

$(OUTDIR)/libUI_interface.so: $(UI_interface_OBJECTS)
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -shared $(UI_interface_OBJECTS) -o $@ $(UI_interface_LIBS)

$(OUTDIR)/libUI.so: $(UI_OBJECTS) $(OUTDIR)/libUI_interface.so
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -L$(TRACKING_LOC)/bin -L$(LOG_LOC)/bin -shared $(UI_OBJECTS) -o $@ $(UI_LIBS)

$(OUTDIR)/libUI_sqlite.so: $(UI_sqlite_OBJECTS) $(OUTDIR)/libUI.so
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -shared $(UI_sqlite_OBJECTS) -o $@ $(UI_sqlite_LIBS)

$(OUTDIR)/libUI_metadata.so: $(UI_metadata_OBJECTS) $(OUTDIR)/libUI_interface.so
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -L$(TRACKING_LOC)/bin -shared $(UI_metadata_OBJECTS) -o $@ $(UI_metadata_LIBS)

$(OUTDIR)/libUI_if_metadata.so: $(UI_if_metadata_OBJECTS) $(OUTDIR)/libUI_interface.so
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -shared $(UI_if_metadata_OBJECTS) -o $@ $(UI_if_metadata_LIBS)

$(OUTDIR)/libUI_inspector.so: $(UI_inspector_OBJECTS) $(OUTDIR)/libUI_interface.so $(OUTDIR)/libUI_if_inspector.so
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -L$(TRACKING_LOC)/bin -shared $(UI_inspector_OBJECTS) -o $@ $(UI_inspector_LIBS)

$(OUTDIR)/libUI_if_inspector.so: $(UI_if_inspector_OBJECTS)
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -shared $(UI_if_inspector_OBJECTS) -o $@ $(UI_if_inspector_LIBS)

$(OUTDIR)/libUI_transient.so: $(UI_transient_OBJECTS) $(OUTDIR)/libUI.so
	$(CXX) $(CXXFLAGS) $(MASLLIB) -L$(OUTDIR) -shared $(UI_transient_OBJECTS) -o $@ $(UI_transient_LIBS)

.o:
	$(CXX) $(CXXFLAGS) -c $<

clean:
	rm -f $(ARTIFACTS) $(SRCDIR)/*.o
