# Target specific macros
TARGET = MentorBot
TARGET_SOURCES := $(wildcard src/*.c)
TOPPERS_OSEK_OIL_SOURCE := ./sumo.oil
BMP_SOURCES := img/splash.bmp

O_PATH ?= build

include ../../ecrobot/ecrobot.mak
