#!/bin/bash
# 
#  This utility is used to run regression tests on these models
#
#   regression_test [-o <output directory>]

# USAGE
print_usage () { 
    echo "Usage:"
    echo "        regression_test [-o <output directory>]";
}

# input variables
BPINSTALL="/build/buildmt/roundtrip/BridgePoint"
OUT_DIR=

# parse arguments
DIRECTIVE=
for arg in $@; do
    if [[ $arg == "-o" ]]; then                     # set the directive
        DIRECTIVE=$arg
    elif [[ $DIRECTIVE == "-o" && $OUT_DIR == "" ]]; then           # only can set the output directory once
        OUT_DIR=$arg
    else
        print_usage
        exit 1
    fi
done

# if no out directory was given, give the current working directory
if [[ $OUT_DIR == "" ]]; then OUT_DIR=.; fi

XVFB=$(which xvfb-run)
if [[ $XVFB == "" ]]; then
  echo "Consider installing xvfb to run this suite headlessly."
fi

# set up workspace
export WORKSPACE="/tmp/importwork"
if [[ -d $WORKSPACE ]]; then
	rm -rf $WORKSPACE
fi

export BPHOME=$BPINSTALL

# lanch eclipse
echo "Launching an Eclipse command line instance..."
$BPINSTALL/tools/mc/bin/CLI.sh Launch

# Run tests
COUNTER=1
while read TEST; do
    if [[ $TEST != "#"* ]]; then
        projects=($TEST)
        if [[ ${#projects[@]} > 1 ]]; then
            # run round trip for a project
            CMD=
            i=0
            while [[ $i < ${#projects[@]} ]]; do
                if [[ $i < $[${#projects[@]} -1] ]]; then
                    CMD="$CMD-d "
                else
                    CMD="$CMD-p "
                fi
                CMD="$CMD${projects[$i]} "
                i=$[$i +1]
            done
            $XVFB $BPINSTALL/tools/mc/bin/masl_round_trip $CMD -o $OUT_DIR/$COUNTER
        else
            # run round trip for a domain
            $XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d $TEST -o $OUT_DIR/$COUNTER
        fi
    fi
    COUNTER=$[$COUNTER +1]
done

# shut down eclipse
$BPINSTALL/tools/mc/bin/CLI.sh Launch -exit

find $OUT_DIR -name "diff_*" -exec ls -l {} \;
find $OUT_DIR -name "diff_*" -exec ls -l {} \; | wc -l
