#!/bin/bash
# 
#  This utility is used to run regression tests on these models
#
#   regression_test [-o <output directory>]

# USAGE
print_usage () { 
    echo "Usage:"
    echo "        regression_test [-o <output directory>]";
}

# input variables
BPINSTALL="/opt/xtuml/BridgePoint6"
OUT_DIR=

# parse arguments
DIRECTIVE=
for arg in $@; do
    if [[ $arg == "-o" ]]; then                     # set the directive
        DIRECTIVE=$arg
    elif [[ $DIRECTIVE == "-o" && $OUT_DIR == "" ]]; then           # only can set the output directory once
        OUT_DIR=$arg
    else
        print_usage
        exit 1
    fi
done

# if no out directory was given, give the current working directory
if [[ $OUT_DIR == "" ]]; then OUT_DIR=.; fi

XVFB=$(which xvfb-run)
if [[ $XVFB == "" ]]; then
  echo "Consider installing xvfb to run this suite headlessly.\n"
fi

# Run tests
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d ../SAC/SAC_OOA -o $OUT_DIR/00
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-1 -o $OUT_DIR/01
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-2 -o $OUT_DIR/02
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-3 -o $OUT_DIR/03
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-4 -o $OUT_DIR/04
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-5 -o $OUT_DIR/05
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d ipv6   -o $OUT_DIR/06
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d pei    -o $OUT_DIR/07
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d maslsupsub -o $OUT_DIR/08
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9149_id -o $OUT_DIR/09
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9151_fref -o $OUT_DIR/10
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9151_fref2 -o $OUT_DIR/11
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9201_enum -o $OUT_DIR/12
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9190_assref -o $OUT_DIR/13
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9192_dupref -o $OUT_DIR/14
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 8507_defer -o $OUT_DIR/15
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9206_refmiss -o $OUT_DIR/16
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9187_poly -o $OUT_DIR/17
#$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d ../SAC/SAC_OOA -p ../SAC/SAC_PROC -o $OUT_DIR/18
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d c_services -o $OUT_DIR/19
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 8938_test -o $OUT_DIR/20
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 8957_test -o $OUT_DIR/21
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d poly -o $OUT_DIR/22
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9252_refass -o $OUT_DIR/23
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9253_secondaryid -o $OUT_DIR/24
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9254_1tomassoc -o $OUT_DIR/25
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9264_current_state -o $OUT_DIR/26
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9272_event_parms -o $OUT_DIR/27
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9275_incomplete -o $OUT_DIR/28
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9276_incomplete -o $OUT_DIR/29
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9280_miss_rows -o $OUT_DIR/30
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9251_default -o $OUT_DIR/31
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9267_assigner -o $OUT_DIR/32
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9297_wrong_obj -o $OUT_DIR/33
#$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d IPv6Nodes -o $OUT_DIR/34
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9316_domain -p 9316_proj -o $OUT_DIR/35
#$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9257_pragma_overload -o $OUT_DIR/36

find . -name "diff_*" -exec ls -l {} \;
