/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_HelloJNI */

#ifndef _Included_test_HelloJNI
#define _Included_test_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_HelloJNI
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_HelloJNI_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
