Source_Structure_Type,Structure,{Source_Integer,Base_Integer_Type;Source_Real,Base_Float_Type;Source_Text,Base_Text_Type;Source_Boolean,Boolean;Source_Colour,Colour_Type}
Colour_Type,Enumeration,{Red,Green,Blue}
Source_Bridge_Data_IH,Root_Object.Object_Access
Very_Simple_Structure_Type,Structure,{Simple_Integer,Base_Integer_Type;Simple_Real,Base_Float_Type}
Very_Simple_Data_Object_IH,Root_Object.Object_Access
Report_Data_IH,Root_Object.Object_Access
Test_Data_IH,Root_Object.Object_Access
Structure_Of_UDTs,Structure,{The_Range,Pos}
Pos,Constrained_User_Type,Base_Integer_Type,1 .. 10
VSD_Struct,Structure,{Ref_Type,Base_Integer_Type;Int_Type,Base_Integer_Type;Real_Type,Base_Float_Type}
IH_Struct,Structure,{The_VSD_IH,Very_Simple_Data_Object_IH}
